### ISSUE TITLE
Upgrade to st 8.1

### ISSUE THREAD

**Issue by Kompwu** [mcaimi/st#1]
There's not much to say... everything is in the title !

**Comment by mcaimi** [comment]
Hi, the codebase has been already updated to match version 0.8.1 :)
You can compare the code to up to this commit [this commit](https://github.com/mcaimi/st/commit/3f16ac2d6dd5f672639c5382bcbd421eb8d8c170). 
I know that the readme still says 0.8 but I'll update that in one of the next updates.
Have i missed something?

**Comment by Kompwu** [comment]
Sounds good, I'll close the issue.
