### ISSUE TITLE
The window goes blank when resized (i3)

### ISSUE THREAD

**Issue by Kompwu** [mcaimi/st#4]
That's very annoying...
I couldn't find a solution.

**Comment by mcaimi** [comment]
I'll have a look. 
Do you use some kind of compositor in you i3 environment? compton, xcompmgr?

**Comment by Kompwu** [comment]
@mcaimi Yes, i'm using compton to get ride of screen tearing.

**Comment by mcaimi** [comment]
@Kompwu No thanks, I use compton too and had just the same bug you reported. I actually use ST always fullscreen so I did not notice the issue.
Anyways, I just committed a fix for the issue, I do not see it happening it anymore. Can you try this?

**Comment by Kompwu** [comment]
@mcaimi It's working perfectly now! :grinning: 
Great job, mate! :+1:
