### ISSUE TITLE
.Xresources not load with -n

### ISSUE THREAD

**Issue by GutsyHeart** [mcaimi/st#9]
![](https://i.ibb.co/P4wDKkS/1577138317.png)
Left default st / Right st -n test

**Comment by mcaimi** [comment]
Can you please detail this issue a little more? What do you expect to see?
If I understood correctly, Xresources are not applied when you start st with the '-n' switch.

That is to be expected, as you are basically adding a new WM_CLASS item to the terminal window.
Xresources from Xrdb are expected to be named <WM NAME>.<RESOURCE NAME>: by default WM_NAME is 'st'.

For example, for property 'color0' you have to set 'st.color0'. If you change the window name with '-n' as per your example, the property that needs to be set is 'test.color0'

I hope I understood this issue. If not, please give me some more details, thanks :)

**Comment by GutsyHeart** [comment]
Yes, you understood the problem correctly.

Thanks. I understood.  '*.color0' is works.

**Comment by mcaimi** [comment]
Ok, good. I'm closing the issue.
Thanks!
